// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: auth.sql

package db_new

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertUser = `-- name: InsertUser :exec
INSERT INTO Users (
	id,email,username,birthdate,password_hash, created, last_seen
) VALUES (
	$1,$2,$3,$4,$5,$6,$7
)
`

type InsertUserParams struct {
	ID           pgtype.UUID
	Email        string
	Username     string
	Birthdate    pgtype.Date
	PasswordHash []byte
	Created      pgtype.Timestamptz
	LastSeen     pgtype.Timestamptz
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.Birthdate,
		arg.PasswordHash,
		arg.Created,
		arg.LastSeen,
	)
	return err
}
