// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: podcast.sql

package db_new

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertPodcast = `-- name: InsertPodcast :exec
INSERT INTO Podcasts(id,title,description,image_url,language,category,explicit,author,link_url,owner_name,owner_email,episodic,copyright,block,complete,pub_date,keywords,summary,rss_url)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19)
`

type InsertPodcastParams struct {
	ID          pgtype.UUID
	Title       string
	Description string
	ImageUrl    string
	Language    string
	Category    []int32
	Explicit    string
	Author      string
	LinkUrl     string
	OwnerName   string
	OwnerEmail  string
	Episodic    pgtype.Bool
	Copyright   string
	Block       pgtype.Bool
	Complete    pgtype.Bool
	PubDate     pgtype.Timestamptz
	Keywords    string
	Summary     string
	RssUrl      string
}

func (q *Queries) InsertPodcast(ctx context.Context, arg InsertPodcastParams) error {
	_, err := q.db.Exec(ctx, insertPodcast,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.ImageUrl,
		arg.Language,
		arg.Category,
		arg.Explicit,
		arg.Author,
		arg.LinkUrl,
		arg.OwnerName,
		arg.OwnerEmail,
		arg.Episodic,
		arg.Copyright,
		arg.Block,
		arg.Complete,
		arg.PubDate,
		arg.Keywords,
		arg.Summary,
		arg.RssUrl,
	)
	return err
}
