version: "3.8"

services:
    db:
        image: postgres:latest
        container_name: db
        restart: always
        environment:
            - POSTGRES_DB=syncapod
            - POSTGRES_USER=syncapod
            - POSTGRES_PASSWORD=${DB_PASS}
        volumes:
            - pg-data:/var/lib/postgresql/data
        networks:
            - backend

    syncapod:
        build:
            context: .
        container_name: syncapod
        restart: always
        volumes:
            - /certs:/certs
        networks:
            - backend
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - db

volumes:
    pg-data:

networks:
    backend:
        driver: bridge
        name: backend
