// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PodClient is the client API for Pod service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PodClient interface {
	// Podcast and Episodes
	GetPodcast(ctx context.Context, in *GetPodReq, opts ...grpc.CallOption) (*Podcast, error)
	GetEpisodes(ctx context.Context, in *GetEpiReq, opts ...grpc.CallOption) (*Episodes, error)
	// UserEpisode
	GetUserEpisode(ctx context.Context, in *GetUserEpiReq, opts ...grpc.CallOption) (*UserEpisode, error)
	UpsertUserEpisode(ctx context.Context, in *UserEpisode, opts ...grpc.CallOption) (*Response, error)
	// Subscriptions
	GetSubscriptions(ctx context.Context, in *GetSubReq, opts ...grpc.CallOption) (*Subscriptions, error)
	UpsertSubscription(ctx context.Context, in *Subscription, opts ...grpc.CallOption) (*Response, error)
	// Misc.
	GetUserLastPlayed(ctx context.Context, in *GetUserLastPlayedReq, opts ...grpc.CallOption) (*LastPlayedRes, error)
}

type podClient struct {
	cc grpc.ClientConnInterface
}

func NewPodClient(cc grpc.ClientConnInterface) PodClient {
	return &podClient{cc}
}

func (c *podClient) GetPodcast(ctx context.Context, in *GetPodReq, opts ...grpc.CallOption) (*Podcast, error) {
	out := new(Podcast)
	err := c.cc.Invoke(ctx, "/protos.Pod/GetPodcast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podClient) GetEpisodes(ctx context.Context, in *GetEpiReq, opts ...grpc.CallOption) (*Episodes, error) {
	out := new(Episodes)
	err := c.cc.Invoke(ctx, "/protos.Pod/GetEpisodes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podClient) GetUserEpisode(ctx context.Context, in *GetUserEpiReq, opts ...grpc.CallOption) (*UserEpisode, error) {
	out := new(UserEpisode)
	err := c.cc.Invoke(ctx, "/protos.Pod/GetUserEpisode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podClient) UpsertUserEpisode(ctx context.Context, in *UserEpisode, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/protos.Pod/UpsertUserEpisode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podClient) GetSubscriptions(ctx context.Context, in *GetSubReq, opts ...grpc.CallOption) (*Subscriptions, error) {
	out := new(Subscriptions)
	err := c.cc.Invoke(ctx, "/protos.Pod/GetSubscriptions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podClient) UpsertSubscription(ctx context.Context, in *Subscription, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/protos.Pod/UpsertSubscription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *podClient) GetUserLastPlayed(ctx context.Context, in *GetUserLastPlayedReq, opts ...grpc.CallOption) (*LastPlayedRes, error) {
	out := new(LastPlayedRes)
	err := c.cc.Invoke(ctx, "/protos.Pod/GetUserLastPlayed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PodServer is the server API for Pod service.
// All implementations must embed UnimplementedPodServer
// for forward compatibility
type PodServer interface {
	// Podcast and Episodes
	GetPodcast(context.Context, *GetPodReq) (*Podcast, error)
	GetEpisodes(context.Context, *GetEpiReq) (*Episodes, error)
	// UserEpisode
	GetUserEpisode(context.Context, *GetUserEpiReq) (*UserEpisode, error)
	UpsertUserEpisode(context.Context, *UserEpisode) (*Response, error)
	// Subscriptions
	GetSubscriptions(context.Context, *GetSubReq) (*Subscriptions, error)
	UpsertSubscription(context.Context, *Subscription) (*Response, error)
	// Misc.
	GetUserLastPlayed(context.Context, *GetUserLastPlayedReq) (*LastPlayedRes, error)
	mustEmbedUnimplementedPodServer()
}

// UnimplementedPodServer must be embedded to have forward compatible implementations.
type UnimplementedPodServer struct {
}

func (UnimplementedPodServer) GetPodcast(context.Context, *GetPodReq) (*Podcast, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPodcast not implemented")
}
func (UnimplementedPodServer) GetEpisodes(context.Context, *GetEpiReq) (*Episodes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEpisodes not implemented")
}
func (UnimplementedPodServer) GetUserEpisode(context.Context, *GetUserEpiReq) (*UserEpisode, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserEpisode not implemented")
}
func (UnimplementedPodServer) UpsertUserEpisode(context.Context, *UserEpisode) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertUserEpisode not implemented")
}
func (UnimplementedPodServer) GetSubscriptions(context.Context, *GetSubReq) (*Subscriptions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSubscriptions not implemented")
}
func (UnimplementedPodServer) UpsertSubscription(context.Context, *Subscription) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertSubscription not implemented")
}
func (UnimplementedPodServer) GetUserLastPlayed(context.Context, *GetUserLastPlayedReq) (*LastPlayedRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserLastPlayed not implemented")
}
func (UnimplementedPodServer) mustEmbedUnimplementedPodServer() {}

// UnsafePodServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PodServer will
// result in compilation errors.
type UnsafePodServer interface {
	mustEmbedUnimplementedPodServer()
}

func RegisterPodServer(s grpc.ServiceRegistrar, srv PodServer) {
	s.RegisterService(&Pod_ServiceDesc, srv)
}

func _Pod_GetPodcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPodReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodServer).GetPodcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Pod/GetPodcast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodServer).GetPodcast(ctx, req.(*GetPodReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pod_GetEpisodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEpiReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodServer).GetEpisodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Pod/GetEpisodes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodServer).GetEpisodes(ctx, req.(*GetEpiReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pod_GetUserEpisode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserEpiReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodServer).GetUserEpisode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Pod/GetUserEpisode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodServer).GetUserEpisode(ctx, req.(*GetUserEpiReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pod_UpsertUserEpisode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserEpisode)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodServer).UpsertUserEpisode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Pod/UpsertUserEpisode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodServer).UpsertUserEpisode(ctx, req.(*UserEpisode))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pod_GetSubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodServer).GetSubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Pod/GetSubscriptions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodServer).GetSubscriptions(ctx, req.(*GetSubReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pod_UpsertSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Subscription)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodServer).UpsertSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Pod/UpsertSubscription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodServer).UpsertSubscription(ctx, req.(*Subscription))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pod_GetUserLastPlayed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserLastPlayedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodServer).GetUserLastPlayed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Pod/GetUserLastPlayed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodServer).GetUserLastPlayed(ctx, req.(*GetUserLastPlayedReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Pod_ServiceDesc is the grpc.ServiceDesc for Pod service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pod_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Pod",
	HandlerType: (*PodServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPodcast",
			Handler:    _Pod_GetPodcast_Handler,
		},
		{
			MethodName: "GetEpisodes",
			Handler:    _Pod_GetEpisodes_Handler,
		},
		{
			MethodName: "GetUserEpisode",
			Handler:    _Pod_GetUserEpisode_Handler,
		},
		{
			MethodName: "UpsertUserEpisode",
			Handler:    _Pod_UpsertUserEpisode_Handler,
		},
		{
			MethodName: "GetSubscriptions",
			Handler:    _Pod_GetSubscriptions_Handler,
		},
		{
			MethodName: "UpsertSubscription",
			Handler:    _Pod_UpsertSubscription_Handler,
		},
		{
			MethodName: "GetUserLastPlayed",
			Handler:    _Pod_GetUserLastPlayed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "podcast.proto",
}
