CREATE TABLE Users (
	id UUID PRIMARY KEY,
	email TEXT NOT NULL UNIQUE,
	username TEXT NOT NULL UNIQUE,
	birthdate DATE NOT NULL,
	password_hash BYTEA NOT NULL
);

CREATE TABLE Sessions (
	id UUID PRIMARY KEY,
	user_id UUID NOT NULL REFERENCES Users(id) ON DELETE CASCADE,
	login_time TIMESTAMPTZ NOT NULL,
	last_seen_time TIMESTAMPTZ NOT NULL,
	expires TIMESTAMPTZ NOT NULL,
	user_agent TEXT NOT NULL
);

CREATE TABLE AuthCodes (
	code BYTEA PRIMARY KEY,
	client_id TEXT NOT NULL,
	user_id UUID NOT NULL REFERENCES Users(id) ON DELETE CASCADE,
	scope TEXT NOT NULL,
	expires TIMESTAMPTZ NOT NULL
);

CREATE TABLE AccessTokens (
	token BYTEA PRIMARY KEY,
	auth_code BYTEA NOT NULL REFERENCES AuthCodes(code) ON DELETE CASCADE,
	refresh_token BYTEA NOT NULL,
	user_id UUID NOT NULL REFERENCES Users(id) ON DELETE CASCADE,
	created TIMESTAMPTZ NOT NULL,
	expires INT NOT NULL
);
