DROP INDEX weighted_pod_idx;
DROP TRIGGER podcasts_search_trigger ON podcasts;
DROP TABLE podcasts_search;
DROP FUNCTION podcasts_search_trigger;
DROP TABLE UserEpisodes;
DROP TABLE Subscriptions;
DROP TABLE Categories;
DROP TABLE Episodes;
DROP TABLE Podcasts;
DROP TABLE PasswordReset;
DROP TABLE Activation;
DROP TABLE AccessTokens;
DROP TABLE AuthCodes;
DROP TABLE Sessions;
DROP TABLE Users;
